### ISSUE TITLE
Remove email validation

### ISSUE THREAD

**Issue by sshvetsov** [traveloka/terraform-aws-acm-certificate#6]
Since Email validation is no longer reliable, nor recommended, we should remove this option from the module and examples.

**Comment by sshvetsov** [comment]
I missed one resource during review:
https://github.com/traveloka/terraform-aws-acm-certificate/blob/350ff8dd557c94726f43f0af32f222c9277d557d/main.tf#L26-L29

This entire block should be removed.

**Comment by SiahaanBernard** [comment]
WIP 
- https://github.com/traveloka/terraform-aws-acm-certificate/pull/10
